### ISSUE TITLE
Getting erros 

### ISSUE THREAD

**Issue by iiseppi** [weatherstorm/Sofaskin-CW9009#22]
Hello,

Getting these errors after installing Sofaskin-CW9009

huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****  'HistoryColors'
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****      obj.start()
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 385, in start
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****      self.run()
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 166, in run
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****      self.init_extensions(gen_dict[section_name])
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 199, in init_extensions
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****      self.search_list_objs.append(klass(self))
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****                                   ^^^^^^^^^^^
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/historygenerator.py", line 53, in __init__
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****      self.color_dict = generator.skin_dict['HistoryColors']
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****                        ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/configobj/__init__.py", line 554, in __getitem__
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****      val = dict.__getitem__(self, key)
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****  KeyError: 'HistoryColors'
huhti 09 10:24:15 weewxsrv-davis python3[138945]: weewx[138945] ERROR weewx.reportengine:         ****  Generator terminated

Images is generated, but not anythink else..

Edit.

weewx version 4.10.2, debian 12 latest amd64.

**Comment by weatherstorm** [comment]
It looks like you are using a new version of historygenerator.py. I haven't updated to the latest version of the script in my skin yet. I would use this [version](https://github.com/weatherstorm/Sofaskin-CW9009/blob/master/bin/user/historygenerator.py) which works up to 5.0.2 thus far. I will look into updating to the latest version soon.

**Comment by iiseppi** [comment]
Ok, I will try to change to that version and report back here. Thx!

**Comment by iiseppi** [comment]
Sorry, forgot to report back, but all good.
